### ISSUE TITLE
1.19.4

### ISSUE THREAD

**Issue by sigaraseviyom** [lilgallon/Bettercolors#108]
When is the version for 1.19.4 coming?

**Comment by lilgallon** [comment]
I thought it was working for 1.19.4, I'm not using it anymore. Thanks for the report, I will update the 1.19.x version to 1.19.4

**Comment by sigaraseviyom** [comment]
thank you so much!

5 May 2023 Cum 10:09 tarihinde Lilian Gallon ***@***.***>
şunu yazdı:

**Comment by lilgallon** [comment]
Here you go: https://github.com/lilgallon/Bettercolors/releases/tag/7.4.1-MC1.19.4fa :)
