### ISSUE TITLE
1.17.1 fabric support

### ISSUE THREAD

**Issue by GithubThrowaway69** [lilgallon/Bettercolors#92]
It would be nice if I could use this lovely mod with 1.17.1 fabric. Do you plan on updating the mod?

**Comment by lilgallon** [comment]
Yeah sure, I'll work on that. I'll try to get it working by the end of the week, I'm super busy lately. The upgrade should be fast to write :)

**Comment by GithubThrowaway69** [comment]
Oh that's great! Please take your time! Don't want to add any stress to your busy schedule!

**Comment by lilgallon** [comment]
To give you an update, it's still on my todo list. Fabric 1.17 requires Java 16, so I need to re-do some stuff on the configuration side. I'll work on it as soon as I get at least 1h of free time.

**Comment by lilgallon** [comment]
Finally done: https://github.com/lilgallon/Bettercolors/releases/tag/7.4.0-MC1.17.1fa

I've got some free time in the upcoming days, hit me up if anything is not wrong
