### ISSUE TITLE
Crash when using aim assistance against mob.

### ISSUE THREAD

**Issue by GithubThrowaway69** [lilgallon/Bettercolors#93]
**Describe the bug:**

Tried out the mod for 1.17.1, when I tried using aim assistance on a zombie or creeper it crashed the game. Crash report attached. Picture of aim assistance settings attached.

**To Reproduce (or what were you doing when it happened):**

Using aim assistance.

Aim assistance setup:

![image](https://user-images.githubusercontent.com/75946024/131226540-c0021186-825e-4e30-a51e-971f78e71fa7.png)

**Crash log:**

[crash-2021-08-28_13.44.35-client.txt](https://github.com/lilgallon/Bettercolors/files/7071189/crash-2021-08-28_13.44.35-client.txt)

- **Have you tried running the mod using the option debug=true**: yes / no
no

- **Have you tried deleting the config files? (minecraft/config/bc_filename.properties)**: yes / no
yes - still crashes.

**Comment by lilgallon** [comment]
Thanks I'll take a look into it. It definitely needs more testing, it must be a dumb mistake since I just ported the current version, I did not remove or add anything new

**Comment by lilgallon** [comment]
Fixed in https://github.com/lilgallon/Bettercolors/releases/tag/7.4.1-MC1.17.1fa
